const jobData = [
    {
      category: "Administrative and Commercial Positions",
      jobs: [
        {
          id: 1,
          title: "Distribution Specialist",
          company: "LogiTech",
          location: "Mumbai",
          salary: "₹5,00,000",
          description: "Manage distribution processes and logistics.",
        },
        {
          id: 2,
          title: "Fine Dining Server",
          company: "Gourmet Delights",
          location: "Delhi",
          salary: "₹3,00,000",
          description:
            "Provide excellent dining service in a fine dining restaurant.",
        },
        {
          id: 3,
          title: "Personal Assistant",
          company: "ExecuServe",
          location: "Bangalore",
          salary: "₹4,50,000",
          description: "Assist executives with daily tasks and scheduling.",
        },
        {
          id: 4,
          title: "Office Manager",
          company: "BizTech",
          location: "Hyderabad",
          salary: "₹6,00,000",
          description: "Oversee daily office operations and staff.",
        },
        {
          id: 5,
          title: "Sales Coordinator",
          company: "MarketMinds",
          location: "Chennai",
          salary: "₹4,20,000",
          description: "Coordinate sales activities and client interactions.",
        },
        {
          id: 6,
          title: "Customer Service Representative",
          company: "HelpHub",
          location: "Pune",
          salary: "₹3,50,000",
          description: "Handle customer inquiries and provide solutions.",
        },
        {
          id: 7,
          title: "Executive Assistant",
          company: "AdminCo",
          location: "Mumbai",
          salary: "₹5,20,000",
          description: "Support senior executives and manage their schedules.",
        },
        {
          id: 8,
          title: "Receptionist",
          company: "FrontDesk Pros",
          location: "Delhi",
          salary: "₹3,70,000",
          description: "Handle front desk operations and guest services.",
        },
      ],
    },
    {
      category: "Engineering and Technical Jobs",
      jobs: [
        {
          id: 10,
          title: "Hydroelectric Specialist",
          company: "EnergyFlow",
          location: "Pune",
          salary: "₹8,00,000",
          description: "Design and manage hydroelectric power projects.",
        },
        {
          id: 11,
          title: "Electrical Engineer",
          company: "ElectraWorks",
          location: "Delhi",
          salary: "₹9,00,000",
          description: "Develop electrical systems and solutions.",
        },
        {
          id: 12,
          title: "Software Developer",
          company: "TechSavvy",
          location: "Bangalore",
          salary: "₹12,00,000",
          description: "Create and maintain software applications.",
        },
        {
          id: 13,
          title: "IT Support Specialist",
          company: "NetFix",
          location: "Mumbai",
          salary: "₹6,50,000",
          description: "Provide technical support for IT systems.",
        },
        {
          id: 14,
          title: "Mechanical Engineer",
          company: "AutoMec",
          location: "Hyderabad",
          salary: "₹10,00,000",
          description: "Design and improve mechanical systems.",
        },
        {
          id: 15,
          title: "Civil Engineer",
          company: "BuildCorp",
          location: "Chennai",
          salary: "₹8,50,000",
          description: "Manage construction and infrastructure projects.",
        },
        {
          id: 16,
          title: "Network Engineer",
          company: "NetSecure",
          location: "Pune",
          salary: "₹7,50,000",
          description: "Design and manage network systems.",
        },
        {
          id: 17,
          title: "Database Administrator",
          company: "DataCorp",
          location: "Delhi",
          salary: "₹9,50,000",
          description: "Maintain and secure database systems.",
        },
      ],
    },
    {
      category: "Healthcare and Medical Careers",
      jobs: [
        {
          id: 19,
          title: "Anesthesiologist",
          company: "MediCare",
          location: "Mumbai",
          salary: "₹15,00,000",
          description: "Administer anesthesia and manage patient care.",
        },
        {
          id: 20,
          title: "Orthodontist",
          company: "SmileRight",
          location: "Delhi",
          salary: "₹18,00,000",
          description: "Provide dental care and corrective treatments.",
        },
        {
          id: 21,
          title: "Clinical Nurse Specialist",
          company: "CarePlus",
          location: "Bangalore",
          salary: "₹12,50,000",
          description: "Advanced nursing care for specialized medical areas.",
        },
        {
          id: 22,
          title: "Clinical Psychologist",
          company: "MindMatters",
          location: "Hyderabad",
          salary: "₹11,00,000",
          description: "Provide psychological assessments and therapy.",
        },
        {
          id: 23,
          title: "Clinical Research Coordinator",
          company: "TrialTech",
          location: "Chennai",
          salary: "₹10,00,000",
          description: "Manage clinical trials and research activities.",
        },
        {
          id: 24,
          title: "Healthcare Administrator",
          company: "HealthCorp",
          location: "Pune",
          salary: "₹9,50,000",
          description: "Oversee operations of healthcare facilities.",
        },
        {
          id: 25,
          title: "Pharmacist",
          company: "PharmaCare",
          location: "Delhi",
          salary: "₹7,00,000",
          description: "Dispense medications and manage pharmacy operations.",
        },
        {
          id: 26,
          title: "Medical Laboratory Technician",
          company: "LabWorks",
          location: "Mumbai",
          salary: "₹6,50,000",
          description: "Conduct laboratory tests and analyze results.",
        },
      ],
    },
    {
      category: "Government and Public Administration Jobs",
      jobs: [
        {
          id: 28,
          title: "Public Safety Officer",
          company: "SafeCity",
          location: "Delhi",
          salary: "₹7,00,000",
          description: "Ensure public safety and security.",
        },
        {
          id: 29,
          title: "City Planner",
          company: "UrbanPlan",
          location: "Mumbai",
          salary: "₹8,50,000",
          description: "Develop plans for urban development.",
        },
        {
          id: 30,
          title: "Administrative Officer",
          company: "AdminDept",
          location: "Bangalore",
          salary: "₹6,00,000",
          description: "Handle administrative tasks for government departments.",
        },
        {
          id: 31,
          title: "Correctional Officer",
          company: "SecureCare",
          location: "Hyderabad",
          salary: "₹6,50,000",
          description: "Maintain security in correctional facilities.",
        },
        {
          id: 32,
          title: "Compliance Officer",
          company: "RegulSafe",
          location: "Chennai",
          salary: "₹7,50,000",
          description: "Ensure compliance with regulations and policies.",
        },
        {
          id: 33,
          title: "Legislative Assistant",
          company: "LegiAssist",
          location: "Pune",
          salary: "₹5,50,000",
          description: "Assist with legislative and policy tasks.",
        },
        {
          id: 34,
          title: "Public Relations Specialist",
          company: "PublicityPro",
          location: "Delhi",
          salary: "₹6,00,000",
          description: "Manage public relations and communications.",
        },
        {
          id: 35,
          title: "Economic Analyst",
          company: "EconoTrend",
          location: "Mumbai",
          salary: "₹8,00,000",
          description: "Analyze economic data and trends.",
        },
       
      ],
    },
    {
      category: "STEM Occupations",
      jobs: [
        {
          id: 37,
          title: "Data Scientist",
          company: "DataWizards",
          location: "Delhi",
          salary: "₹14,00,000",
          description: "Analyze data and derive insights.",
        },
        {
          id: 38,
          title: "Machine Learning Engineer",
          company: "AIHub",
          location: "Bangalore",
          salary: "₹15,00,000",
          description: "Develop machine learning models and algorithms.",
        },
        {
          id: 39,
          title: "Biotechnologist",
          company: "BioTech",
          location: "Mumbai",
          salary: "₹12,00,000",
          description: "Work on biotechnological innovations and research.",
        },
        {
          id: 40,
          title: "Environmental Scientist",
          company: "EcoGuard",
          location: "Hyderabad",
          salary: "₹10,00,000",
          description: "Study environmental issues and solutions.",
        },
        {
          id: 41,
          title: "Robotics Engineer",
          company: "RoboWorks",
          location: "Chennai",
          salary: "₹11,50,000",
          description: "Design and develop robotic systems.",
        },
        {
          id: 42,
          title: "Quantitative Analyst",
          company: "QuantLab",
          location: "Pune",
          salary: "₹13,00,000",
          description: "Analyze financial data using quantitative methods.",
        },
        {
          id: 43,
          title: "Bioinformatics Specialist",
          company: "BioInfoTech",
          location: "Delhi",
          salary: "₹11,00,000",
          description: "Apply data analysis techniques to biological data.",
        },
        {
          id: 44,
          title: "Energy Analyst",
          company: "EnergyInsight",
          location: "Mumbai",
          salary: "₹9,00,000",
          description: "Analyze energy data and trends.",
        },
      ],
    },
    {
      category: "Creative and Design Careers",
      jobs: [
        {
          id: 46,
          title: "Graphic Designer",
          company: "DesignX",
          location: "Delhi",
          salary: "₹6,00,000",
          description: "Create visual content and designs.",
        },
        {
          id: 47,
          title: "UX/UI Designer",
          company: "UserFirst",
          location: "Bangalore",
          salary: "₹7,00,000",
          description: "Design user interfaces and improve user experiences.",
        },
        {
          id: 48,
          title: "Content Writer",
          company: "ContentWorks",
          location: "Mumbai",
          salary: "₹5,50,000",
          description: "Create engaging and informative content.",
        },
        {
          id: 49,
          title: "Video Editor",
          company: "EditPro",
          location: "Hyderabad",
          salary: "₹6,50,000",
          description: "Edit and produce video content.",
        },
        {
          id: 50,
          title: "Art Director",
          company: "Artistry",
          location: "Chennai",
          salary: "₹8,00,000",
          description: "Oversee visual aspects of creative projects.",
        },
        {
          id: 51,
          title: "Web Designer",
          company: "WebCraft",
          location: "Pune",
          salary: "₹6,00,000",
          description: "Design and develop websites.",
        },
        {
          id: 52,
          title: "Brand Strategist",
          company: "Brandify",
          location: "Delhi",
          salary: "₹7,50,000",
          description: "Develop branding strategies and campaigns.",
        },
        {
          id: 53,
          title: "Illustrator",
          company: "DrawIt",
          location: "Mumbai",
          salary: "₹5,80,000",
          description: "Create illustrations for various media.",
        },
      ],
    },
    {
      category: "Finance and Business Management",
      jobs: [
        {
          id: 55,
          title: "Financial Analyst",
          company: "FinancePro",
          location: "Delhi",
          salary: "₹8,00,000",
          description: "Analyze financial data and trends.",
        },
        {
          id: 56,
          title: "Business Development Manager",
          company: "GrowthX",
          location: "Bangalore",
          salary: "₹10,00,000",
          description: "Identify and develop new business opportunities.",
        },
        {
          id: 57,
          title: "Accountant",
          company: "AccountMasters",
          location: "Mumbai",
          salary: "₹6,00,000",
          description: "Manage financial records and transactions.",
        },
        {
          id: 58,
          title: "Investment Banker",
          company: "InvestBank",
          location: "Hyderabad",
          salary: "₹12,00,000",
          description: "Manage investment portfolios and financial transactions.",
        },
        {
          id: 59,
          title: "Project Manager",
          company: "ProjectX",
          location: "Chennai",
          salary: "₹9,00,000",
          description:
            "Oversee and manage projects from initiation to completion.",
        },
        {
          id: 60,
          title: "Risk Manager",
          company: "RiskGuard",
          location: "Pune",
          salary: "₹7,50,000",
          description: "Identify and mitigate financial risks.",
        },
        {
          id: 61,
          title: "Financial Controller",
          company: "FinanceCo",
          location: "Delhi",
          salary: "₹9,50,000",
          description: "Oversee financial operations and reporting.",
        },
        {
          id: 62,
          title: "Business Analyst",
          company: "BizInsight",
          location: "Mumbai",
          salary: "₹8,50,000",
          description: "Analyze business processes and provide solutions.",
        },
      ],
    },
    {
      category: "Education and Training",
      jobs: [
        {
          id: 64,
          title: "Teacher",
          company: "EduLearn",
          location: "Delhi",
          salary: "₹5,00,000",
          description: "Educate and support students in various subjects.",
        },
        {
          id: 65,
          title: "Training Coordinator",
          company: "TrainTech",
          location: "Bangalore",
          salary: "₹6,00,000",
          description: "Coordinate and organize training programs.",
        },
        {
          id: 66,
          title: "Academic Advisor",
          company: "Academia",
          location: "Mumbai",
          salary: "₹5,50,000",
          description: "Advise students on academic programs and career paths.",
        },
        {
          id: 67,
          title: "Curriculum Developer",
          company: "CurriculPro",
          location: "Hyderabad",
          salary: "₹6,50,000",
          description: "Develop educational curricula and materials.",
        },
        {
          id: 68,
          title: "Educational Consultant",
          company: "ConsultEdu",
          location: "Chennai",
          salary: "₹7,00,000",
          description:
            "Provide consulting services for educational institutions.",
        },
        {
          id: 69,
          title: "Special Education Teacher",
          company: "SpecEd",
          location: "Pune",
          salary: "₹5,80,000",
          description: "Teach and support students with special needs.",
        },
        {
          id: 70,
          title: "Language Instructor",
          company: "LangLearn",
          location: "Delhi",
          salary: "₹5,50,000",
          description: "Teach foreign languages and communication skills.",
        },
        {
          id: 71,
          title: "Education Program Manager",
          company: "EduPlan",
          location: "Mumbai",
          salary: "₹6,00,000",
          description: "Manage and oversee educational programs and initiatives.",
        },
      ],
    },
    {
      category: "Sales and Marketing Jobs",
      jobs: [
        {
          id: 73,
          title: "Sales Executive",
          company: "SalesPlus",
          location: "Delhi",
          salary: "₹6,00,000",
          description: "Drive sales and manage client relationships.",
        },
        {
          id: 74,
          title: "Marketing Coordinator",
          company: "MarketPlus",
          location: "Bangalore",
          salary: "₹5,50,000",
          description: "Coordinate marketing activities and campaigns.",
        },
        {
          id: 75,
          title: "Product Manager",
          company: "ProductX",
          location: "Mumbai",
          salary: "₹7,50,000",
          description: "Manage product development and marketing.",
        },
        {
          id: 76,
          title: "Digital Marketer",
          company: "DigitalPro",
          location: "Hyderabad",
          salary: "₹6,50,000",
          description: "Develop and execute digital marketing strategies.",
        },
        {
          id: 77,
          title: "Account Manager",
          company: "ClientCare",
          location: "Chennai",
          salary: "₹6,00,000",
          description: "Manage client accounts and sales.",
        },
        {
          id: 78,
          title: "SEO Specialist",
          company: "SEOBoost",
          location: "Pune",
          salary: "₹5,80,000",
          description: "Optimize websites for search engines.",
        },
        {
          id: 79,
          title: "Market Research Analyst",
          company: "MarketInsight",
          location: "Delhi",
          salary: "₹6,00,000",
          description: "Conduct market research and analyze trends.",
        },
        {
          id: 80,
          title: "Brand Manager",
          company: "BrandWorks",
          location: "Mumbai",
          salary: "₹7,00,000",
          description: "Manage and develop brand strategies.",
        },
      ],
    },
    {
      category: "Customer Service and Support",
      jobs: [
        {
          id: 82,
          title: "Customer Support Specialist",
          company: "SupportX",
          location: "Delhi",
          salary: "₹4,50,000",
          description: "Assist customers with inquiries and resolve issues.",
        },
        {
          id: 83,
          title: "Help Desk Technician",
          company: "TechHelp",
          location: "Bangalore",
          salary: "₹4,00,000",
          description: "Provide technical support and assistance.",
        },
        {
          id: 84,
          title: "Client Relations Manager",
          company: "ClientFirst",
          location: "Mumbai",
          salary: "₹5,00,000",
          description: "Manage client relationships and ensure satisfaction.",
        },
        {
          id: 85,
          title: "Support Services Coordinator",
          company: "SupportPro",
          location: "Hyderabad",
          salary: "₹4,80,000",
          description: "Coordinate support services and client interactions.",
        },
        {
          id: 86,
          title: "Technical Support Specialist",
          company: "TechAid",
          location: "Chennai",
          salary: "₹4,70,000",
          description: "Provide technical support and solutions.",
        },
        {
          id: 87,
          title: "Customer Experience Manager",
          company: "ExperienceX",
          location: "Pune",
          salary: "₹5,50,000",
          description: "Enhance customer experience and satisfaction.",
        },
        {
          id: 88,
          title: "Support Analyst",
          company: "SupportTech",
          location: "Delhi",
          salary: "₹4,60,000",
          description: "Analyze and resolve customer support issues.",
        },
        {
          id: 89,
          title: "Customer Service Manager",
          company: "ServicePro",
          location: "Mumbai",
          salary: "₹5,20,000",
          description: "Oversee customer service operations and team.",
        },
      ],
    },
  ];
  
  export default jobData;